name: Scheduled PowerShell Job

on:
  schedule:
    - cron: "48 16 * * 0/6"
  workflow_dispatch:      # also allow manual trigger

jobs:
  run-powershell:
    runs-on: windows-latest  # Windows Server runner
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repo        
        uses: actions/checkout@v4
      - name: Run PowerShell script
        shell: pwsh
        run: .\scripts\UnfollowTest1.ps1